//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 10:00:25 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://javaops.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package src.main.java.ru.javaops.masterjava.xml.schema;
