//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 08:17:58 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://javaops.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.javaops.masterjava.xml.schema;
